<?php
/**
 * @file
 * sl_ct_faq.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function sl_ct_faq_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function sl_ct_faq_node_info() {
  $items = array(
    'faq' => array(
      'name' => t('FAQ'),
      'base' => 'node_content',
      'description' => t('Contenu de type Foire Aux Questions. Permet de rédiger un article sous forme de question/réponse'),
      'has_title' => '1',
      'title_label' => t('Titre'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
