<?php
/**
 * Implements hook_block_info().
 */
function ddd_newsletter_block_info() {
  $blocks['block_newsletter'] = array(
    'info' => t('Sign in to newsletter'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ddd_newsletter_block_view($delta = '') {
  $block = array();
	if($delta === 'block_newsletter') {
	  $block['subject'] = '';
	  $block['content'] = theme('block--block-newsletter');
	}
	return $block;
}

/**
 * Implements hook_theme().
 */
function ddd_newsletter_theme($existing, $type, $theme, $path) {
  return array(
    'block--block-newsletter' => array(
      'template' => 'themes/block--block-newsletter'
    )
  );
}
?>