<?php
/**
 * @file
 * ddd_ct_blog.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function ddd_ct_blog_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function ddd_ct_blog_node_info() {
  $items = array(
    'blog' => array(
      'name' => t('Blog'),
      'base' => 'node_content',
      'description' => t('Type de contenu regroupant les actualités, les articles de presses, les offres de stage et d\'emploi ainsi que les questions/réponses.'),
      'has_title' => '1',
      'title_label' => t('Titre'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
